server:
  port: 8100
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  application:
    name: idea-app-backend

  # For JSON beautiful response during development
  jackson:
    serialization:
      indent-output: true
